version: 3

tasks:
  build: go build -o ./out/bin/updater main.go

  run:
    - task: build
    - ./out/bin/updater

  schema: go run share/configuration/gen/main.go > share/configuration/schema.json
