version: 3

tasks:
  pwd:
    cmd: pwd

  build-cli:
    cmd: go build -o ./out/bin/client ./cmd/client/main.go

  build:
    vars:
      TASK_NAME:
        sh: task get_name
      PWD:
        sh: task pwd
    cmd: go build  -o ./out/bin/{{.TASK_NAME}} main.go

  get_name_windows:
    platforms:
      - "windows"
    cmd: echo "updater.exe"
  get_name_linux:
    platforms:
      - "linux"
    cmd: echo "updater"
  get_name:
    cmds:
      - task: get_name_windows
      - task: get_name_linux

  run:
    - task: build
    - ./out/bin/updater

  upver:
    - python upver.py
